In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
import numpy as np

In [4]:
corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]

> TF(t) = (Number of times term t appears in a document) / (Total number of terms in the document)            

> IDF(t) = log_e(Total number of documents / Number of documents with term t in it).             

> Value = TF * IDF

In [5]:
vectorizer = TfidfVectorizer()

In [6]:
X = vectorizer.fit_transform(corpus)

In [7]:
X.shape

(4, 9)

In [8]:
X

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [9]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [10]:
X.todense()[0]

matrix([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
         0.        , 0.38408524, 0.        , 0.38408524]])

In [11]:
X.todense()[0].shape

(1, 9)

In [9]:
X.todense()

matrix([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
         0.        , 0.38408524, 0.        , 0.38408524],
        [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
         0.53864762, 0.28108867, 0.        , 0.28108867],
        [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
         0.        , 0.26710379, 0.51184851, 0.26710379],
        [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
         0.        , 0.38408524, 0.        , 0.38408524]])

# first sentence

> TF(t) = (Number of times term t appears in a document) / (Total number of terms in the document)            

> IDF(t) = log_e(**1** + Total number of documents / **1** + Number of documents with term t in it) + **1**             

> Value = TF * IDF

In [10]:
#TF(t) = (Number of times term t appears in a document) / (Total number of terms in the document)


# Number of times term t appears in a document) = 1/ Total number of terms in the document) = 5

1/5

0.2

In [11]:
#IDF(t) = log_e( 1 + Total number of documents / 1 + Number of documents with term t in it) + 1

In [12]:
idf = vectorizer.idf_
print(dict(zip(vectorizer.get_feature_names(), idf)))

{'and': 1.916290731874155, 'document': 1.2231435513142097, 'first': 1.5108256237659907, 'is': 1.0, 'one': 1.916290731874155, 'second': 1.916290731874155, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.0}


In [13]:
import math

In [14]:
math.log( (1+ 4)/(1+2) )  + 1

1.5108256237659907

In [15]:
corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]

In [16]:
first = (1/5) * ( math.log( (1+ 4)/(1+2) )  + 1 )

In [17]:
document = (1/5) * ( math.log( (1+ 4)/(1+3) )  + 1 )

In [18]:
is_ = (1/5) * ( math.log( (1+ 4)/(1+4) )  + 1 )

In [19]:
the_ =  (1/5) * ( math.log( (1+ 4)/(1+4) )  + 1 )

In [20]:
this_ =  (1/5) * ( math.log( (1+ 4)/(1+4) )  + 1 )

In [21]:
vec =[0, document, first, is_, 0, 0, the_, 0, this_]

In [22]:
vec

[0, 0.24462871026284194, 0.3021651247531982, 0.2, 0, 0, 0.2, 0, 0.2]

In [23]:
vec /  np.linalg.norm(vec)

array([0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
       0.        , 0.38408524, 0.        , 0.38408524])

In [24]:
X.todense()[0]

matrix([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
         0.        , 0.38408524, 0.        , 0.38408524]])

In [26]:
l2 = vec /  np.linalg.norm(vec)

In [27]:
np.linalg.norm(l2)

1.0