<div class="alert alert-block alert-info">  
<h1><strong>Word Embeddings</strong></h1>
</div>

<div class="alert alert-block alert-info">  
<h2><strong>Imports</strong></h2>
</div>

In [40]:
import numpy as np
import spacy
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
# Need to load the large model to get the vectors
nlp = spacy.load('en_core_web_lg')

In [42]:
nlp.vocab.vectors.shape[0] / 1e3,nlp.vocab.vectors.shape[1]

(684.83, 300)

<div class="alert alert-block alert-info">  
<h1><strong>Queen</strong></h1>
    <p>Comparison between Queen , King , Mother and Princess
    </p>
</div>

In [43]:
nlp("queen").vector[:10]

array([ 0.4095 , -0.22693,  0.25362, -0.36055, -0.37095, -0.35181,
        0.50669, -0.77897, -0.32571,  1.4895 ], dtype=float32)

In [44]:
nlp("queen").vector.shape

(300,)

In [45]:
cosine_similarity([nlp("queen").vector],[nlp("king").vector])

array([[0.725261]], dtype=float32)

In [46]:
cosine_similarity([nlp("queen").vector],[nlp("mother").vector])

array([[0.44720313]], dtype=float32)

In [47]:
cosine_similarity([nlp("queen").vector],[nlp("princess").vector])

array([[0.6578181]], dtype=float32)

<div class="alert alert-block alert-info">  
<h1><strong>Software consultant</strong></h1>
    <p>Comparison between Software consultant ,data guy and plumber
    </p>
</div>

In [48]:
x1 = nlp("I am a software consultant").vector
x2 = nlp("Hey ,me  data guy").vector
x3 = nlp("Hey ,me  plumber").vector

In [49]:
x1.shape , x2.shape , x3.shape

((300,), (300,), (300,))

In [50]:
cosine_similarity([x1],[x2])

array([[0.7383951]], dtype=float32)

In [51]:
cosine_similarity([x1],[x3])

array([[0.64217263]], dtype=float32)

<div class="alert alert-block alert-info">  
<h1><strong>Pepsi</strong></h1>
    <p>Comparison between Pepsi , Coke , Sprite, Chips , Potato Chips and Teacher
    </p>
</div>

In [52]:
cosine_similarity([nlp("pepsi").vector],[nlp("coke").vector])

array([[0.6556941]], dtype=float32)

In [53]:
cosine_similarity([nlp("pepsi").vector],[nlp("sprite").vector])

array([[0.39027715]], dtype=float32)

In [54]:
cosine_similarity([nlp("pepsi").vector],[nlp("chips").vector])

array([[0.24748442]], dtype=float32)

In [55]:
cosine_similarity([nlp("pepsi").vector],[nlp("teacher").vector])

array([[-0.00911483]], dtype=float32)

In [56]:
cosine_similarity([nlp("pepsi").vector],[nlp("potato chips").vector])

array([[0.29382914]], dtype=float32)